### ISSUE TITLE
new d4w beta 1.13.0-rc3 9266

### ISSUE THREAD

**Issue by StefanScherer** [riezebosch/BoxstarterPackages#11]
I got an update message for the Docker 4 Windows Beta, now 1.13.0-rc3 9266
Don't have a Windows machine at hand to update and send a PR.

**Comment by riezebosch** [comment]
1.13.0.9266-rc3 would make a good version number for the nuspec?

**Comment by StefanScherer** [comment]
In the about window it's called 1.13.0-rc3-beta32 (9266)

So people see "beta 32" and/or the docker version "1.13.0-rc3"

What about

1.13.0-rc3-beta32.9266

Should be still be a prerelease as there are dashes and characters in it.
And so the the imaginary final
1.13.0.9999
should be newer than one of these beta version numbers.

**Comment by riezebosch** [comment]
`'1.13.0-rc3-beta32.9266' is not a valid version string.`

**Comment by StefanScherer** [comment]
1.13.0.9266-rc3-beta32 ?
But can we retrieve the "rc3" and "beta32" from the MSI? I cannot remember.

**Comment by riezebosch** [comment]
It just pulls the version number from the MSI (which is `1.13.0.9266`) but I could modify the nuspec by hand.

Name | Type
------|------
Docker for Windows (Install) 1.13.0.9266-rc3 | release candidate
Docker for Windows (Install) 1.13.0.9123-beta | beta release
Docker for Windows (Install) 1.12.3.8711-beta  | beta release
Docker for Windows (Install) 1.12.3.8488 | official release

The 1.12.4-RC1 ([link](https://github.com/docker/docker/releases)) doesn't really fit into this scheme, but is that version even available on a download channels? I guess I better keep things simple and stick to `1.13.0.9266-beta` after all. In the end, that's the channel where the download comes from.

**Comment by StefanScherer** [comment]
Sure, automation over manual configuration. 😀

**Comment by riezebosch** [comment]
Done
