### ISSUE TITLE
Add packageSourceUrl

### ISSUE THREAD

**Issue by pascalberger** [riezebosch/BoxstarterPackages#16]
It would be nice to have packageSourceUrl added to the `nuspec` files so that there is a link from the Chocolatey Package site to this repository.

**Comment by riezebosch** [comment]
Sure! Which package are you referring to?

**Comment by pascalberger** [comment]
I saw that it's missing for the KB2919442 and KB2919355 packages

**Comment by riezebosch** [comment]
I'm a bit reluctant in updating these because of the massive downloads. I don't want it to be on each and every machine getting uninstalled (not sure if that's the case) and reinstalled only for adding this metadata.

**Comment by pascalberger** [comment]
@riezebosch You might add it and wait for pushing a new version of the package until other changes are made. But in any case upgrading one of the KB packages should not be an issue since it should just skip the installation (Chocolatey shouldn't uninstall the old package version AFAIK)

**Comment by FranklinYu** [comment]
Package source URL is missing in several packages, such as `MsSqlServerSchoolSampleDatabase` and `aspnet5`. In addition the SoapUI package lacks source URL https://github.com/SmartBear/soapui.
