### ISSUE TITLE
Invalid checksum for docker-for-windows-beta

### ISSUE THREAD

**Issue by lucastheisen** [riezebosch/BoxstarterPackages#18]
According to the official [download page](https://download.docker.com/win/edge/Docker%20for%20Windows%20Installer.exe.sha256sum), the current checksum is: 
```
65d962a94ddfd0018ecceadb06c870c0ffdf6b6748aee31cacd8c087efe4743a  Docker for Windows Installer.exe
```
Your [code has it listed as](https://github.com/riezebosch/BoxstarterPackages/blob/master/docker-for-windows-beta/tools/chocolateyinstall.ps1#L15):
```
    checksum = 'C9CA352161A94A21A5D2763781C82585A0DFFEF0AF9F367EF544213BD3C91346'
```
Perhaps it would be better to replace that line with:
```
    checksum = (Invoke-WebRequest https://download.docker.com/win/edge/Docker%20for%20Windows%20Installer.exe.sha256sum).Content.Split(' ')[0]
```

**Comment by razi-rais** [comment]
Facing exactly the same issue. Simple fix would be to update the checksum but considering docker edge release cycle is more frequent better approach would be similar to what is suggested by @lucastheisen. Its does provide bit more future proofing.

**Comment by riezebosch** [comment]
Had a chat on [this topic](https://ci.appveyor.com/project/riezebosch/boxstarterpackages/build/4) a while ago in the chocolatey gitter channel but the checksum is considered [a layer of defense](https://gitter.im/chocolatey/choco?at=580aa1a3a3bbf12d562646ab). Downloading it at install time would defeat that purpose. <s>The proper fix would be turning this into an automated package so it gets updated automatically from an CI server.</s>

[Auto Update](https://github.com/riezebosch/BoxstarterPackages/commit/a66ad14ae72943d1e856b4557690faea51c42a64) from [AppVeyor](https://ci.appveyor.com/project/riezebosch/boxstarterpackages/)!

**Comment by riezebosch** [comment]
Found the source where the _new_ installer retrieves it information: https://download.docker.com/win/edge/appcast.xml

Turns out there's also a channel for the stable release:
 https://download.docker.com/win/stable/appcast.xml.

From that information there seems to be an .EXE installer already that currently is only promoted in the Windows Server 2016 Edge channel!

That installer seems to be working fine on Windows 10 and is the version the _Edge_ package already uses (as per [request](https://chocolatey.org/packages/docker-for-windows#comment-3313660352)). It has nice features like stopping the VM and upgrading in place without losing your containers.

Should we switch over to the new installer already or should we wait until it gets published on the Docker store site?

@StefanScherer Opinions on this matter?

**Comment by StefanScherer** [comment]
@riezebosch I don't know the differences between the MSI and EXE installers. 
Having a working choco package for both Win10 and Server 2016 would be a good thing.
But I don't know if users run into trouble when choco package uses the EXE on Win10.

I suggest to keep it in sync the the https://store.docker.com/editions/community/docker-ce-desktop-windows download links.

So maybe switching in the chocolateyInstall.ps1 

On a Windows Server 2016 machine:
```
PS C:\> $(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' ProductName).ProductName
Windows Server 2016 Datacenter
```

On a Windows 10 machine:
```
PS C:\> $(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' ProductName).ProductName
Windows 10 Enterprise
```

So this could be a trigger

```powershell
if ($(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' ProductName).ProductName.StartsWith("Windows 10")) {
  "Use MSI"
} else {
  "Use EXE"
}
```

I don't know the plans if Docker switches to EXE installer in the future.

**Comment by riezebosch** [comment]
I've created an issue with exactly that question: https://github.com/docker/for-win/issues/954. I'm a bit hesitant to add all kind of complexity to the package because it seems that this is exactly where the EXE installer is designed for.

**Comment by StefanScherer** [comment]
That's a good idea, I hope you get some clarification to keep choco package as simple as possible.

**Comment by riezebosch** [comment]
I've added the same Auto Updater to the stable package but for now it uses the same MSI installer as offered from the download page. The only difference is the direct link to the specific version but the checksums are the same.
