### ISSUE TITLE
Long Term Support (v1.1.4)

### ISSUE THREAD

**Issue by AnthonyMastrean** [riezebosch/BoxstarterPackages#23]
I need packages for LTS 1.1.4. I suggest a branch from the last 1.1.2 changes and a PR just for reviewing. If it's OK, you can pull the branch over and build & publish the LTS packages from there.

https://www.microsoft.com/net/download/windows

----

See https://github.com/jberezanski/dotnetcore-chocolateypackages/issues/16

**Comment by riezebosch** [comment]
Maybe have a separate package called dotnetcore-sdk-lts with a pinned version dependency on dotnetcore-sdk?

**Comment by AnthonyMastrean** [comment]
I was thinking the same thing 👍

**Comment by riezebosch** [comment]
I see: https://github.com/jberezanski/dotnetcore-chocolateypackages/pull/18#issuecomment-344724394 😄
