### ISSUE TITLE
Update docker-desktop to 2.0.0.0-win81 (29211) 

### ISSUE THREAD

**Issue by pascalberger** [riezebosch/BoxstarterPackages#28]
There seems to be a new version of the Docker Desktop package 2.0.0.0-win81 (Build 29211) available (I get notified through Docker in-app update.

Also it seems like there are multiple versions of Docker Deskotp 2.0.0.0 (`2.0.0.0-win78` and `2.0.0.0-win81`). It would be nice if the Chocolatey package could be updated for every of these version (But `2.0.0.0-win78` would not be a good version number as this would imply a pre-release)

**Comment by riezebosch** [comment]
The docker versioning scheme is killing me 😢

**Comment by pascalberger** [comment]
Don't know whats the best way to move forward. There's a unique build id, which could be integrated, but they already have 4 digits in the version number...

**Comment by riezebosch** [comment]
It turns out to be a fault on the [docker side](https://github.com/docker/for-win/issues/3069#issuecomment-445802974) and a new version is to be expected within two weeks. I think we'll have to wait for that because otherwise, we'll interfere with the newly released version number since all digits are already taken.

**Comment by StefanScherer** [comment]
Docker Desktop 2.0.1.0 has been released on edge. I didn't know that there still is the edge channel.

https://download.docker.com/win/edge/30090/Docker%20Desktop%20Installer.exe

**Comment by riezebosch** [comment]
> Docker Desktop 2.0.1.0 has been released on edge. I didn't know that there still is the edge channel.
> 
> https://download.docker.com/win/edge/30090/Docker%20Desktop%20Installer.exe

Published.

**Comment by StefanScherer** [comment]
Thanks 🎉  Now people can try out `--isolation=process` on a Windows 10 1809 machine.

**Comment by riezebosch** [comment]
It's there: https://chocolatey.org/packages/docker-desktop/2.0.0.2 🎈🍰
