### ISSUE TITLE
SQLLocalDb package needs to be updated

### ISSUE THREAD

**Issue by brianary** [riezebosch/BoxstarterPackages#31]
SqlLocalDB seems to be up to v14.1805.4072.1, so the current version (14.0.1000.169) needs to be updated.

[Finding the direct download URL of **SqlLocalDB.msi** is hard.](https://stackoverflow.com/a/42952186/54323) I'm not having any luck with Fiddler, otherwise I'd submit a PR to update the [URL](https://github.com/riezebosch/BoxstarterPackages/blob/master/sqllocaldb/tools/chocolateyinstall.ps1#L4 "BoxstarterPackages/sqllocaldb/tools/chocolateyinstall.ps1 $url") and checksum.

**Comment by riezebosch** [comment]
https://download.microsoft.com/download/B/C/1/BC1933D9-9F9B-4453-A65F-F474E7EA1AE8/SqlLocalDB.msi

Guess that's the one?

**Comment by brianary** [comment]
That one looks 🇩🇪 German, but I think the version is right.

**Comment by riezebosch** [comment]
Found it, after some digging: https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SqlLocalDB.msi. But that is the same as already in the package? This is the one I extract from the latest sql express installer!

**Comment by brianary** [comment]
That looks good! SqlLocalDB 2017 14.0.1000.169.

**Comment by riezebosch** [comment]
But that one's already in the current package as far as I can see?!

**Comment by brianary** [comment]
Yeah, and now that I check the actual install, that's the same version as the German one.

That's odd because [**SQLServer2017-SSEI-Expre.exe**](https://www.microsoft.com/en-us/sql-server/sql-server-editions-express) (the downloader) has a file and product version of 14.1805.4072.1, but actually downloads **SqlLocalDB.msi** 14.0.1000.169.

Thanks for checking. Sorry, I should have checked this closer before filing an issue.

**Comment by riezebosch** [comment]
No problem.
