### ISSUE TITLE
Cannot upgrade SQL-Server-Express

### ISSUE THREAD

**Issue by Kuinox** [riezebosch/BoxstarterPackages#38]
Hello,
Currently sql-server-express cannot be upgraded.
Because the service run in background, the install script fail, and in the logfile i can read "Instance name 'SQLEXPRESS' is already in use. To continue, specify a unique instance name.".

By reading the docs, it looks like it's feasible to ugprade, but i need to look more into this:
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-to-a-different-edition-of-sql-server-setup?view=sql-server-ver15

If you don't plan to support upgrade, it would be nice to add a log in the console to say that it need manual upgrade.

**Comment by riezebosch** [comment]
That's correct. I never managed to create a decent uninstall script so you'll have to do that yourself. Should definitely be added to the package description.

**Comment by Kuinox** [comment]
I can't find how chocolatey do packages upgrade, but i think it's just calling the Install script.   
Adding instances detection & running the upgrade script should be enough.   
The big question for me, is, is it safe to update the sql instance.

**Comment by riezebosch** [comment]
As far as I'm aware it invokes the uninstall script of currently installed packages first.

**Comment by Kuinox** [comment]
Sadly i didn't found in the doc something specifying it, but i remember reading that it does behaved this way. By reading the logs, it looks like it's only running the install script now.
