### ISSUE TITLE
Docker Desktop updated itself and now choco upgrade fails

### ISSUE THREAD

**Issue by and-semakin** [riezebosch/BoxstarterPackages#48]
Hi! Huge thanks for publishing the `docker-desktop` package!

I have an issue with it. Seems like my Docker has automatically upgraded itself and now `choco upgrade all` command fails because of it.

See log output here: https://gist.github.com/and-semakin/40ca6b750ba9fe5582b04550d96ed6f0

I understand that I should probably disable this auto-update feature and let `choco` manage it for me, but it's turned on by default and I didn't even notice how it upgraded itself (probably it asked and I just pressed ok). Is this an expected behavior? Shouldn't install script exit with success code if such situation appears?

**Comment by riezebosch** [comment]
I looked through the logs but I'm not sure if I can do something about that in the package since the exit code from the installer is very generic: `3`. You can probably circumvent this problem yourself by invoking chocolatey with the `-n` while doing the upgrade to skip the installer script and only register a new package.

**Comment by and-semakin** [comment]
Thanks for your response!

Just an idea: is it possible to use the output of the installer to decide if the process is successful or not? I can imagine that it's a way full of pain. Seems like `GoogleChrome` is able to detect if Chrome is already up-to-date and finish without errors (Chrome updates itself from time to time).

Anyway, solved the issue on my side & disabled the Docker's auto-update feature to prevent the same thing from happening in the future as I try to manage everything using `choco`. Didn't know about `-n` flag.

Feel free to close the issue or keep it for now :)
