### ISSUE TITLE
sql-server-express uninstall depends on gui

### ISSUE THREAD

**Issue by bryanwieg** [riezebosch/BoxstarterPackages#52]
Thanks for your work on this amazing tool.

I was using this package via ssh and Windows Server 2019 Core. So, no Desktop GUI, total pwsh command prompt only.

Installed works great. On uninstall, however, Choco would hang. Took a while to figure out the uninstall was calling a GUI Window that depending on the user clicking a button. This GUI would only appear when RDP into the host.

It _is_ possible to do a sql server uninstall without a gui. Comparing these lines might help:

https://github.com/riezebosch/BoxstarterPackages/blob/ba2ea1b3d33c714b98c64eb51ca6ec50b0e36dd9/sql-server-express/tools/chocolateyuninstall.ps1#L6-L7

Compared to another package for SQL Server Developer:

https://github.com/flcdrg/au-packages/blob/master/sql-server-2019/tools/chocolateyuninstall.ps1#L5

I didn't dig fully into it, but the key looks like it may lie in not using 'SetupARP.exe' and instead using 'Setup.exe' with the flags on line 11:

https://github.com/flcdrg/au-packages/blob/master/sql-server-2019/tools/chocolateyuninstall.ps1#L11

Thank you again.

**Comment by riezebosch** [comment]
Will give it a try. What I remember is that you have to specify which features to uninstall and that depends a little on what was specified during installation and could therefore vary.
