### ISSUE TITLE
SOAP UI urls differ between x64 and x32

### ISSUE THREAD

**Issue by istairbn** [riezebosch/BoxstarterPackages#58]
The sources are different. Currently x32 gets from the eviware site, whereas x64 goes direct to an AWS S3 bucket. 
If you're behind a proxy, that would mean whitelisting s3.amazonaws.com.... which is a pretty large one.

The package is on eviware too, so we should be consistent. PR to follow

**Comment by riezebosch** [comment]
merged and pushed https://community.chocolatey.org/packages/soapui/5.7.0.20220304
